[package]
name = "poke-type-desktop"
version = "0.1.1"
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.3", features = [] }
tauri-plugin-updater = "2.10.1"
serde_json.workspace = true
