import {launchDesktop} from './launch';
import {test, expect} from '@playwright/test';
import {mkdtemp, readFile, writeFile, cp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import type {BootstrapData} from '../../packages/core/types';

test('实际本地规则重建、候选检查、激活、保留旧队伍及迁移冲突', async () => {
  test.setTimeout(120000);
  const directory = await mkdtemp(join(tmpdir(), 'poke-rules-ui-'));
  const source = join(directory, 'showdown-source');
  await cp(resolve('.upstream/pokemon-showdown-aa17ca0fac8bc5605df673bd8774c2d0e91efa43'), source, {recursive: true});
  const file = join(source, 'config/formats.ts'); const formats = await readFile(file, 'utf8');
  const name = 'name: "[Gen 9 Champions] VGC 2026 Reg M-C",';
  expect(formats).toContain(name); await writeFile(file, formats.replace(name, `${name}\n\t\tbanlist: ['Rillaboom'],`));
  const dexFile = join(source, 'data/pokedex.ts'); const dex = await readFile(dexFile, 'utf8');
  await writeFile(dexFile, dex.replace('hp: 95, atk: 135, def: 80, spa: 110, spd: 80, spe: 100', 'hp: 95, atk: 136, def: 80, spa: 110, spd: 80, spe: 100'));
  const chartFile = join(source, 'data/typechart.ts'); const chart = await readFile(chartFile, 'utf8');
  await writeFile(chartFile, chart.replace(/(\trock: \{[\s\S]*?\t\t\tWater:) 1,/, '$1 0,'));
  const app = await launchDesktop(directory);
  try {
    const page = await app.firstWindow();
    const b: BootstrapData = JSON.parse(await readFile('assets/bootstrap.json', 'utf8'));
    const team = b.corpus.teams.find(t => t.url.includes('73e5d6533b781089'))!;
    await page.getByRole('button', {name: '导入', exact: true}).click();
    await page.getByLabel('Showdown 队伍文本').fill(team.raw); await page.getByRole('button', {name: '解析队伍'}).click(); await page.getByRole('button', {name: '开始构筑'}).click();
    await page.getByRole('button', {name: '环境', exact: true}).click();
    await page.locator('.environment-management>summary').click();
    await page.getByRole('button', {name: '使用本地 Showdown 文件'}).click();
    await page.getByLabel('本地 Showdown 目录').fill(source);
    const started = performance.now();
    await page.getByRole('button', {name: '读取并验证本地规则'}).click();
    await expect(page.locator('.update-preview')).toBeVisible({timeout: 90000});
    const preparedMs = performance.now() - started;
    await expect(page.locator('.update-preview')).toContainText('轰擂金刚猩');
    await expect(page.locator('.update-preview')).toContainText('16 档乱数');
    const before = await page.evaluate(() => window.poke.call('bootstrap', undefined));
    expect(before.activeEnvironmentId).toBe(b.environment.id);
    await page.getByRole('button', {name: '启用这个环境', exact: true}).click();
    await expect(page.locator('.update-preview').getByRole('button', {name: '已启用'})).toBeVisible();
    const updated = await page.evaluate(() => window.poke.call('bootstrap', undefined));
    expect(updated.activeEnvironmentId).not.toBe(b.environment.id); expect(updated.environments).toHaveLength(2);
    expect(updated.drafts.some(d => d.environmentId === b.environment.id && d.members.length === 6)).toBe(true);
    expect(updated.environment.speciesIds).not.toContain('rillaboom');
    expect(updated.dex.species.find(s => s.id === 'salamence')!.stats.atk).toBe(136);
    await page.getByLabel('管理与同步的数据环境').selectOption(updated.activeEnvironmentId);
    await page.getByText('管理分表与后续赛季', {exact: true}).click();
    await expect(page.getByLabel('分表1gid')).toBeVisible();
    await page.getByLabel('分表1gid').fill('99999999');
    await page.getByRole('button', {name: '保存来源设置'}).click();
    await expect(page.getByText('来源注册表已保存', {exact: true})).toBeVisible();
    await page.getByLabel('管理与同步的数据环境').selectOption(b.environment.id);
    await expect(page.getByLabel('分表1gid')).toHaveValue(b.corpus.reports[0].gid);
    const attacker = b.model.archetypes.find(a => a.speciesId === 'basculegion' && a.representative.moves.includes('wavecrash'))!.representative;
    const defender = b.model.archetypes.find(a => a.speciesId === 'tyranitar')!.representative;
    const damageAt = (environmentId: string) => page.evaluate(input => window.poke.call('damage', input), {attacker, defender, environmentId, field: {weather: 'Rain'}});
    const oldDamage = (await damageAt(b.environment.id)).find(r => r.moveId === 'wavecrash')!;
    const newDamage = (await damageAt(updated.activeEnvironmentId)).find(r => r.moveId === 'wavecrash')!;
    // Life Orb rounds after type effectiveness, so the final damage need not be exactly linear.
    expect(oldDamage.max).toBeGreaterThan(newDamage.max);
    expect(Math.abs(oldDamage.max - newDamage.max * 2)).toBeLessThanOrEqual(1);
    await page.getByRole('button', {name: '迁移当前队伍'}).click();
    await expect(page.getByRole('dialog')).toContainText('Rillaboom');
    await page.getByRole('button', {name: '创建迁移后的队伍'}).click();
    await expect(page.getByRole('dialog')).toBeHidden();
    await expect(page.getByText('已自动保存', {exact: true})).toBeVisible();
    const after = await page.evaluate(() => window.poke.call('bootstrap', undefined));
    expect(after.drafts.filter(d => d.members.length === 6)).toHaveLength(2);
    expect(new Set(after.drafts.filter(d => d.members.length === 6).map(d => d.environmentId)).size).toBe(2);
    console.log(JSON.stringify({ruleUpdate: {executable: process.env.POKE_EXECUTABLE ?? 'source', preparedMs, verifiedWorkflowMs: performance.now() - started}}));
    await page.screenshot({path: 'test-results/rule-update.png'});
  } finally {await app.close();}
});
