import {test, expect} from '@playwright/test';
import {mkdtemp, readFile, rm} from 'node:fs/promises';
import {join, resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {launchDesktop} from './launch';
import {Store} from '../../packages/core/storage';
import {BattleEngine} from '../../packages/core/battle/engine';
import {fitModel} from '../../packages/core/analysis/model';
import {revalidateCorpus} from '../../packages/core/sources/revalidate';
import type {BootstrapData} from '../../packages/core/types';

test('零样本赛季显示历史配置、保存开关，并以历史对手完成真实模拟', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'poke-history-ui-'));
  const bootstrap: BootstrapData = JSON.parse(await readFile('assets/bootstrap.json', 'utf8'));
  const source = bootstrap.corpus.teams.find(team => team.season === 'M-B' && team.status === 'valid')!;
  const engine = new BattleEngine(resolve('assets/engines', bootstrap.engine.id), bootstrap.environment.formatId, bootstrap.translations);
  const corpus = revalidateCorpus({...bootstrap.corpus, teams: [source]}, engine);
  const model = fitModel(corpus, engine, undefined, false);
  const store = new Store(directory, resolve('assets'));
  store.install({...bootstrap, corpus, model}); store.close();
  let app = await launchDesktop(directory);
  try {
    let page = await app.firstWindow();
    await page.getByLabel('搜索宝可梦').fill(engine.name('species', corpus.observations[0].set.speciesId));
    await page.getByRole('option').first().click();
    await expect(page.getByLabel('包括历史合法配置')).toBeChecked();
    await expect(page.locator('.historical-reference')).toContainText('当前有 0 份独立完整观察');
    await expect(page.locator('.configuration-card').first()).toContainText('历史迁移');
    await page.getByLabel('包括历史合法配置').uncheck();
    await expect(page.locator('.configuration-card')).toHaveCount(0);
    await page.getByLabel('包括历史合法配置').check();
    await page.getByRole('button', {name: '加入', exact: true}).first().click();
    await expect(page.getByTestId('team-member')).toHaveCount(1);
    await page.getByText('推荐偏好与保留变体', {exact: true}).click();
    await page.getByLabel('允许推荐历史合法配置').uncheck();
    await page.getByRole('button', {name: '保存推荐偏好'}).click();
    await expect(page.locator('.search-preferences')).toContainText('已保存');
    await page.getByRole('button', {name: '寻找搭档', exact: true}).click();
    await expect(page.getByRole('alert')).toContainText('当前赛季没有符合条件的完整配置');
    await app.close(); app = await launchDesktop(directory); page = await app.firstWindow();
    await page.getByText('推荐偏好与保留变体', {exact: true}).click();
    await expect(page.getByLabel('允许推荐历史合法配置')).not.toBeChecked();
    await page.getByRole('button', {name: '导入', exact: true}).click();
    await page.getByLabel('Showdown 队伍文本').fill(source.raw);
    await page.getByRole('button', {name: '解析队伍'}).click(); await page.getByRole('button', {name: '开始构筑'}).click();
    await expect(page.getByTestId('team-member')).toHaveCount(6);
    await page.getByRole('tab', {name: '深入评估'}).click();
    await expect(page.locator('.simulation-sources')).toContainText('参考 M-B');
    await page.getByLabel('无当前完整队伍时参考历史对手').uncheck();
    await expect(page.locator('.simulation-sources')).toContainText('没有完整合法对手');
    await page.getByLabel('无当前完整队伍时参考历史对手').check();
    await page.getByLabel('固定场数（可复现）').check();
    await page.getByText('策略与计算预算', {exact: true}).click();
    await page.getByLabel('训练场数', {exact: true}).fill('0'); await page.getByLabel('复评场数', {exact: true}).fill('1');
    await page.getByRole('button', {name: '开始深入评估'}).click();
    await expect(page.locator('.job-status')).toContainText('完成');
    await expect(page.locator('.simulation-evidence')).toContainText('历史样本');
    const jobs = await page.evaluate(() => window.poke.call('jobs', undefined));
    const job = jobs.find(job => job.kind === 'simulate')!;
    expect(job.status).toBe('completed');
    expect(job.result && 'wins' in job.result && job.result.opponentEvidence?.seasons).toEqual(['M-B']);
    await page.screenshot({path: 'test-results/history-cold-start.png'});
  } finally {await app.close(); await rm(directory, {recursive: true, force: true});}
});
