import {launchDesktop} from './launch';
import {test, expect, type ElectronApplication} from '@playwright/test';
import {mkdtemp, readFile, mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import type {BootstrapData} from '../../packages/core/types';

test('核心构筑、方案比较、撤销、保存恢复与窄窗口', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'poke-ui-'));
  const launch = () => launchDesktop(directory);
  let app: ElectronApplication = await launch();
  try {
    let page = await app.firstWindow();
    page.on('pageerror', error => console.error('renderer:', error.message));
    await expect(page.getByLabel('搜索宝可梦')).toBeVisible();
    await page.screenshot({path: 'test-results/workspace-empty.png'});
    await page.getByLabel('搜索宝可梦').fill('大狃拉');
    await page.getByLabel('搜索宝可梦').dispatchEvent('keydown', {key: 'Enter', code: 'Enter', isComposing: true});
    await expect(page.getByRole('option', {name: '选择大狃拉的配置'})).toBeVisible();
    await page.getByRole('option', {name: '选择大狃拉的配置'}).click();
    await page.getByRole('button', {name: '加入', exact: true}).first().click();
    await expect(page.getByTestId('team-member')).toHaveCount(1);
    await page.getByRole('button', {name: '锁定大狃拉核心', exact: true}).click();
    await expect(page.getByRole('button', {name: '解锁大狃拉核心', exact: true})).toHaveAttribute('aria-pressed', 'true');
    await page.getByLabel('队伍名称').fill('核心构筑验收');
    await page.getByRole('button', {name: '生成完整方案', exact: true}).first().click();
    await expect(page.locator('.proposal-card').first()).toBeVisible({timeout: 25000});
    await page.locator('.proposal-card').first().getByRole('button', {name: '比较并应用'}).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await expect(page.locator('.lineup-comparison')).toContainText('面对同一对手，选出如何变化');
    await expect(page.locator('.lineup-comparison')).toContainText('快速矩阵覆盖流派概率');
    await page.locator('.lineup-comparison').scrollIntoViewIfNeeded();
    await page.screenshot({path: 'test-results/lineup-comparison.png'});
    await page.getByRole('button', {name: '应用这个方案'}).click();
    await expect(page.getByTestId('team-member')).toHaveCount(6);
    await expect(page.getByRole('button', {name: '解锁大狃拉核心', exact: true})).toBeVisible();
    await page.getByRole('button', {name: '撤销修改'}).click();
    await expect(page.getByTestId('team-member')).toHaveCount(1);
    await page.getByRole('button', {name: '重做修改'}).click();
    await expect(page.getByTestId('team-member')).toHaveCount(6);
    await page.getByRole('button', {name: '导出队伍', exact: true}).click();
    await expect(page.getByLabel('导出的 Showdown 队伍')).toContainText('EVs:');
    await page.getByRole('dialog').getByRole('button', {name: '关闭', exact: true}).click();
    await expect(page.getByText('已自动保存', {exact: true})).toBeVisible();
    await page.screenshot({path: 'test-results/workspace-complete.png'});
    const native = await app.browserWindow(page); await native.evaluate(window => window.setSize(840, 890));
    await expect(page.getByRole('button', {name: '构筑推荐', exact: false})).toBeVisible();
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({path: 'test-results/workspace-narrow.png'});
    await app.close();
    app = await launch(); page = await app.firstWindow();
    await expect(page.getByLabel('队伍名称')).toHaveValue('核心构筑验收');
    await expect(page.getByTestId('team-member')).toHaveCount(6);
    await expect(page.getByRole('button', {name: '解锁大狃拉核心', exact: true})).toBeVisible();
    await page.getByRole('button', {name: '环境', exact: true}).click();
    await expect(page.getByText('Champions M-C', {exact: true})).toBeVisible();
    await expect(page.getByText('184 份来源', {exact: true})).toBeVisible();
    await page.screenshot({path: 'test-results/environment.png'});
  } finally {await app.close();}
});
