import {createPortal} from 'react-dom';
import {useEffect, useRef, useState} from 'react';
import {ArrowLeft, ArrowRight, Check, ChevronDown, CircleCheck, CircleHelp, Clipboard, Download, FolderHeart, Globe2, LayoutDashboard, LoaderCircle, Plus, Redo2, Search, Settings2, Sparkles, Undo2, Upload, X} from 'lucide-react';
import type {BattleField, PokemonSet, Proposal, SourceTeam, TeamMember} from '../../../../packages/core/types';
import {useWorkspace} from './useWorkspace';
import {BrandMark} from './BrandMark';
import {DexProvider, IconButton, Modal, PokemonIcon, SourceDetail, Spinner, newMember} from './ui';
import {Catalog} from './Catalog';
import {Builder, ProposalPreview, Recommendations} from './Builder';
import {MemberEditor} from './MemberEditor';
import {DamageDrawer} from './DamageDrawer';
import {SourceIntentEditor} from './SourceIntentEditor';
import {Environment} from './Environment';
import {MyTeams} from './MyTeams';
import {ModelUpdateProgress} from './ModelUpdateProgress';

export default function App() {
  const w = useWorkspace(); const [page, setPage] = useState<'build' | 'environment' | 'teams'>('build');
  const [editor, setEditor] = useState<TeamMember | null>(null); const [proposal, setProposal] = useState<Proposal | null>(null); const [source, setSource] = useState<SourceTeam | null>(null); const [damage, setDamage] = useState<{attacker: PokemonSet; defender: PokemonSet; field?: BattleField} | null>(null);
  const [catalogOpen, setCatalogOpen] = useState(false); const [recommendationsOpen, setRecommendationsOpen] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const [importing, setImporting] = useState(false); const [importText, setImportText] = useState(''); const [parsed, setParsed] = useState<{sets: PokemonSet[]; issues: string[]} | null>(null); const [replaceImport, setReplaceImport] = useState(false); const [importBusy, setImportBusy] = useState(false);
  const [exporting, setExporting] = useState(false); const [exportText, setExportText] = useState(''); const [copied, setCopied] = useState(false);
  const openSearch = () => {setPage('build'); if (window.innerWidth < 1220) setCatalogOpen(true); else inputRef.current?.focus();};
  useEffect(() => {const keydown = (event: KeyboardEvent) => {if (event.isComposing) return; const target = event.target as HTMLElement; const editing = ['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName) || target.isContentEditable; if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') {event.preventDefault(); openSearch();} else if (!editing && (event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'z') {event.preventDefault(); if (event.shiftKey) w.redo(); else w.undo();} else if (!editing && event.key === '/') {event.preventDefault(); openSearch();}}; window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown);}, [w.undo, w.redo]);
  const add = (set: PokemonSet) => {if (!w.draft || !w.state) return; if (w.draft.members.length >= w.state.environment.teamSize) {w.setError('队伍已满，可以在成员编辑中移出一位，或比较替换建议。'); return;} const m = newMember(set); w.edit(d => ({...d, members: [...d.members, m]})); setCatalogOpen(false); if (!set.points || set.moves.length !== 4) setEditor(m);};
  const parseImport = async () => {if (!w.state) return; setImportBusy(true); try {setParsed(await window.poke.call('parse', {text: importText, environmentId: w.state.environment.id}));} catch (err) {w.report(err);} finally {setImportBusy(false);}};
  const applyImport = async () => {if (!parsed?.sets.length) return; try {if (replaceImport) w.edit(d => ({...d, members: parsed.sets.map(newMember)})); else await w.create(parsed.sets, '导入的队伍', w.state!.environment.id); setImporting(false); setParsed(null); setImportText(''); setPage('build');} catch (err) {w.report(err);}};
  const importSource = async (team: SourceTeam) => {try {const result = await window.poke.call('parse', {text: team.raw, environmentId: w.state!.environment.id}); const sets = result.sets.map((set, slot): PokemonSet => ({...set, sourceKind: team.season === w.state!.environment.season ? 'observed' : 'historical', sourceIds: [`${team.id}:${slot}`]})); await w.create(sets, `${team.author || team.id.split(':')[1]} · 构筑`, w.state!.environment.id); setSource(null); setPage('build');} catch (err) {w.report(err);}};
  const exportTeam = async () => {if (!w.draft) return; try {await w.flush(); setExportText(await window.poke.call('export', w.draft)); setExporting(true); setCopied(false);} catch (err) {w.report(err);}};
  const modelJob = w.jobs.find(job => job.kind === 'model' && job.status === 'running');
  if (!w.state || !w.draft) return <div className="boot-screen"><div className="brand-badge large"><BrandMark size={54}/></div><h1>结阵 Sixfold</h1>{w.error ? <><p role="alert">{w.error}</p><button className="button primary" onClick={() => location.reload()}>重新加载本地数据</button></> : modelJob ? <ModelUpdateProgress job={modelJob} onError={w.report}/> : <Spinner label="读取规则与本地队伍…"/>}</div>;
  const {state, draft} = w;
  const compare = (p: Proposal) => {setProposal(p); setRecommendationsOpen(false);};
  return <DexProvider dex={state.dex}><div className="app-shell"><nav className="app-nav" aria-label="主要导航"><button className="brand-button" aria-label="结阵 Sixfold 首页" onClick={() => setPage('build')}><BrandMark size={36}/></button><div className="nav-items">{([{id: 'build', label: '构筑', icon: LayoutDashboard}, {id: 'environment', label: '环境', icon: Globe2}, {id: 'teams', label: '我的队伍', icon: FolderHeart}] as const).map(n => <button key={n.id} className={page === n.id ? 'selected' : ''} onClick={() => setPage(n.id)} aria-current={page === n.id ? 'page' : undefined}><n.icon size={21}/><span>{n.label}</span></button>)}</div><div className="nav-bottom"><span className="local-indicator" title="本地存储"><span/>LOCAL</span><button aria-label="环境和数据设置" title="环境和数据设置" onClick={() => setPage('environment')}><Settings2 size={20}/></button></div></nav><div className="app-main"><header className="topbar"><div className="team-title"><span className="breadcrumb">{page === 'build' ? '构筑工作台' : page === 'environment' ? '环境与数据' : '我的收藏'}<span>/</span></span><input aria-label="队伍名称" value={draft.name} onChange={e => w.edit(d => ({...d, name: e.target.value}))}/></div><button className="environment-pill" onClick={() => setPage('environment')}><span className="live-dot"/>{state.environment.season}<span>双打</span></button><div className={`save-status ${w.saved}`} aria-live="polite">{w.saved === 'saved' ? <><CircleCheck size={14}/><span>已自动保存</span></> : w.saved === 'saving' ? <><LoaderCircle size={14} className="spin"/><span>保存中</span></> : <span>保存失败</span>}</div><div className="topbar-actions"><div className="history-actions"><IconButton label="撤销修改" disabled={!w.canUndo} onClick={w.undo}><Undo2 size={17}/></IconButton><IconButton label="重做修改" disabled={!w.canRedo} onClick={w.redo}><Redo2 size={17}/></IconButton></div><button className="button quiet" aria-label="导入" onClick={() => {setImporting(true); setParsed(null);}}><Upload size={15}/><span>导入</span></button><button className="button dark" onClick={() => void exportTeam()}><Download size={15}/><span>导出队伍</span></button></div></header>
    {modelJob && <ModelUpdateProgress job={modelJob} onError={w.report}/>}
    {w.error && createPortal(<div className="app-error" role="alert"><span>{w.error}</span><IconButton label="关闭错误提示" onClick={() => w.setError('')}><X size={17}/></IconButton></div>, document.getElementById('notifications')!)}
    {page === 'build' ? <div className="workspace-grid"><div className="desktop-catalog"><Catalog state={state} currentSpecies={draft.members.map(m => m.set.speciesId)} onAdd={add} onSource={setSource} inputRef={inputRef}/></div><Builder onProposal={compare} workspace={w} onEdit={setEditor} onSearch={openSearch} onDamage={(attacker, defender, field) => setDamage({attacker, defender, field})} onSource={setSource}/><div className="desktop-recommendations"><Recommendations workspace={w} onCompare={compare}/></div><div className="mobile-actions"><button onClick={openSearch}><Search size={17}/>搜索成员</button><button onClick={() => setRecommendationsOpen(true)}><Sparkles size={17}/>构筑推荐{w.proposals.length > 0 && <span>{w.proposals.length}</span>}</button></div></div> : page === 'environment' ? <Environment workspace={w} onSource={setSource}/> : <MyTeams workspace={w} onOpen={() => setPage('build')}/>}
    </div></div>
    <Modal open={catalogOpen} onClose={() => setCatalogOpen(false)} title="选择构筑素材" drawer><Catalog state={state} currentSpecies={draft.members.map(m => m.set.speciesId)} onAdd={add} onSource={setSource} onClose={() => setCatalogOpen(false)}/></Modal>
    <Modal open={recommendationsOpen} onClose={() => setRecommendationsOpen(false)} title="构筑推荐" drawer><Recommendations workspace={w} onCompare={compare}/></Modal>
    <MemberEditor member={editor} workspace={w} onReplace={id => {setEditor(null); if (window.innerWidth <= 1000) setRecommendationsOpen(true); void w.recommend('replace', id);}} onClose={() => setEditor(null)} onDamage={(attacker, defender, field) => setDamage({attacker, defender, field})} onSource={setSource}/><DamageDrawer pair={damage} workspace={w} onClose={() => setDamage(null)}/><ProposalPreview proposal={proposal} workspace={w} onClose={() => setProposal(null)}/><SourceDetail team={source} onClose={() => setSource(null)} onImport={t => void importSource(t)}>{source && <SourceIntentEditor key={source.id} team={source} w={w}/>}</SourceDetail>
    <Modal open={importing} onClose={() => setImporting(false)} title="导入已有队伍" description={`粘贴 Showdown 文本。EVs 按 Champions ${state.environment.season} 能力点解释，不会自动换算。`} wide>{!parsed ? <><textarea className="paste-input" aria-label="Showdown 队伍文本" value={importText} onChange={e => setImportText(e.target.value)} placeholder={'Rillaboom @ Miracle Seed\nAbility: Grassy Surge\nLevel: 50\nEVs: 24 HP / 32 Atk / 10 SpD\nAdamant Nature\n- Fake Out\n- Grassy Glide\n- Wood Hammer\n- U-turn'}/><div className="dialog-footer"><span className="muted">可以先导入不足六只的核心草稿</span><button className="button primary" disabled={!importText.trim() || importBusy} onClick={() => void parseImport()}>{importBusy ? <Spinner/> : <>解析队伍 <ArrowRight size={15}/></>}</button></div></> : <><h3>识别到 {parsed.sets.length} 位成员</h3><div className="import-preview">{parsed.sets.map((s, i) => <div key={i}><PokemonIcon id={s.speciesId} size={64}/><strong>{state.dex.species.find(p => p.id === s.speciesId)?.zh || s.speciesId}</strong><span>{s.points ? '配点已提供' : '配点未知'}</span></div>)}</div>{parsed.issues.length > 0 && <div className="notice warning">{parsed.issues.map((issue, i) => <p key={i}>{issue}</p>)}</div>}<label className="checkbox-label"><input type="checkbox" checked={replaceImport} onChange={e => setReplaceImport(e.target.checked)}/>替换当前队伍（不勾选则建立新队伍）</label><div className="dialog-footer"><button className="button secondary" onClick={() => setParsed(null)}><ArrowLeft size={15}/>返回修改文本</button><button className="button primary" disabled={!parsed.sets.length} onClick={() => void applyImport()}>开始构筑</button></div></>}</Modal>
    <Modal open={exporting} onClose={() => setExporting(false)} title="导出队伍" description={`${draft.name} · ${state.environment.season} · Champions 能力点`}><textarea className="paste-input export-text" aria-label="导出的 Showdown 队伍" value={exportText} readOnly/><div className="dialog-footer"><button className="button secondary" onClick={() => void window.poke.saveText(`${draft.name}.txt`, exportText).catch(w.report)}><Download size={15}/>保存文件</button><button className="button primary" onClick={() => void navigator.clipboard.writeText(exportText).then(() => setCopied(true)).catch(w.report)}>{copied ? <><Check size={15}/>已复制</> : <><Clipboard size={15}/>复制队伍文本</>}</button></div></Modal>
  </DexProvider>;
}
