import {useMemo, useState, useRef, useEffect, useId} from 'react';
import {ArrowLeft, ChevronRight, Search, SlidersHorizontal, X, BookOpen} from 'lucide-react';
import type {AppState, PokemonSet, SourceTeam} from '../../../../packages/core/types';
import {useDex, PokemonIcon, TypeBadge, IconButton} from './ui';
import {ConfigurationBrowser} from './ConfigurationBrowser';
import {configurationMechanisms, MECHANISMS} from '../../../../packages/core/analysis/mechanisms';
import {MechanismFilters} from './MechanismFilters';

export function Catalog({state, currentSpecies, onAdd, onSource, onClose, inputRef}: {state: AppState; currentSpecies: string[]; onAdd: (set: PokemonSet) => void; onSource: (source: SourceTeam) => void; onClose?: () => void; inputRef?: React.RefObject<HTMLInputElement | null>}) {
  const dex = useDex(); const [query, setQuery] = useState(''); const [speciesId, setSpeciesId] = useState<string | null>(null);
  const [mechanismId, setMechanismId] = useState<string | null>(null); const [active, setActive] = useState(0); const [filters, setFilters] = useState(false);
  const speciesByMechanism = useMemo(() => {
    const index = new Map(MECHANISMS.map(rule => [rule.id, new Set<string>()]));
    for (const c of state.configurations) for (const {rule} of configurationMechanisms(c.set, dex.speciesById.get(c.speciesId))) index.get(rule.id)!.add(c.speciesId);
    return index;
  }, [state.configurations, dex.speciesById]);
  const selectedMechanism = MECHANISMS.find(rule => rule.id === mechanismId);
  const countBySpecies = useMemo(() => {const counts = new Map<string, number>(); for (const a of state.configurations) counts.set(a.speciesId, (counts.get(a.speciesId) || 0) + a.currentCount); return counts;}, [state.configurations]);
  const roster = useMemo(() => dex.species.filter(s => `${s.name} ${s.zh} ${s.id}`.toLowerCase().includes(query.toLowerCase()) && (!mechanismId || speciesByMechanism.get(mechanismId)!.has(s.id))).sort((a, b) => (countBySpecies.get(b.id) || 0) - (countBySpecies.get(a.id) || 0) || a.zh.localeCompare(b.zh, 'zh-CN')), [dex.species, query, mechanismId, countBySpecies, speciesByMechanism]);
  const species = speciesId ? dex.speciesById.get(speciesId) : null;

  const alreadyIn = currentSpecies.includes(speciesId || '');
  const resultsId = useId(); const listRef = useRef<HTMLDivElement>(null);
  useEffect(() => {listRef.current?.querySelector<HTMLElement>('[aria-selected="true"]')?.scrollIntoView({block: 'nearest'});}, [active, roster, speciesId]);
  return <aside className="catalog"><div className="panel-title"><span><Search size={17}/>构筑素材</span>{onClose ? <IconButton label="收起搜索" onClick={onClose}><X size={17}/></IconButton> : <span className="keycap">Ctrl K</span>}</div><div className="catalog-search"><Search size={16}/><input ref={inputRef} role="combobox" aria-autocomplete="list" aria-controls={!species ? resultsId : undefined} aria-expanded={!species} aria-activedescendant={!species && roster[active] ? `${resultsId}-${active}` : undefined} aria-label="搜索宝可梦" placeholder="搜索宝可梦，中英文均可" value={query} onChange={e => {setQuery(e.target.value); setSpeciesId(null); setActive(0);}} onKeyDown={e => {if (e.nativeEvent.isComposing || e.keyCode === 229) return; if (e.key === 'ArrowDown') {e.preventDefault(); setActive(i => Math.min(i + 1, Math.max(0, roster.length - 1)));} else if (e.key === 'ArrowUp') {e.preventDefault(); setActive(i => Math.max(0, i - 1));} else if (e.key === 'Enter' && roster[active]) {e.preventDefault(); setSpeciesId(roster[active].id);} else if (e.key === 'Escape') setSpeciesId(null);}}/>{query && <IconButton label="清空搜索" onClick={() => {setQuery(''); inputRef?.current?.focus();}}><X size={13}/></IconButton>}</div>
    {!species && <><div className="catalog-subheading"><span>{query ? `${roster.length} 个搜索结果` : `${state.environment.season} 规则内的宝可梦`}</span><IconButton label="筛选功能" active={filters} onClick={() => setFilters(!filters)}><SlidersHorizontal size={15}/></IconButton></div>{filters && <MechanismFilters selected={mechanismId} speciesByMechanism={speciesByMechanism} onSelect={id => {setMechanismId(id); setActive(0);}}/>}{selectedMechanism && <div className="active-mechanism"><span>{selectedMechanism.label}</span><IconButton label="清除机制筛选" onClick={() => {setMechanismId(null); setActive(0);}}><X size={13}/></IconButton></div>}<div ref={listRef} id={resultsId} className="catalog-roster" role="listbox" aria-label="宝可梦搜索结果">{roster.map((s, i) => <button id={`${resultsId}-${i}`} key={s.id} role="option" tabIndex={-1} aria-selected={i === active} onMouseDown={e => e.preventDefault()} className={`species-row ${i === active ? 'highlight' : ''}`} onClick={() => setSpeciesId(s.id)} aria-label={`选择${s.zh}的配置`}><PokemonIcon id={s.id} size={45}/><div className="species-name"><strong>{s.zh}</strong><span>{s.name}</span><div className="types">{s.types.map(t => <TypeBadge key={t} type={t}/>)}</div></div><div className="species-count">{currentSpecies.includes(s.id) ? <span className="in-team">已加入</span> : <><b>{countBySpecies.get(s.id) || '—'}</b><small>当前观察</small></>}<ChevronRight size={13}/></div></button>)}{!roster.length && <div className="empty-inline">没有匹配的宝可梦或功能配置。</div>}</div><div className="catalog-footnote"><BookOpen size={13}/><span>数字仅统计当前赛季共享样本<br/>不代表排位使用率</span></div></>}
    {species && <div className="archetypes"><button className="text-button back" onClick={() => setSpeciesId(null)}><ArrowLeft size={14}/>返回宝可梦</button><div className="species-profile"><div className="portrait" style={{'--portrait-color': `var(--type-${species.types[0].toLowerCase()}, #eee9fb)`} as React.CSSProperties}><PokemonIcon id={species.id} size={92}/></div><h2>{species.zh}</h2><p>{species.name}</p><div className="types">{species.types.map(t => <TypeBadge key={t} type={t}/>)}</div></div><ConfigurationBrowser key={`${species.id}:${state.model.version}:${mechanismId}`} state={state} speciesId={species.id} mechanismId={mechanismId} disabled={alreadyIn || currentSpecies.length >= state.environment.teamSize} onAdd={onAdd} onSource={onSource}/><button className="button secondary full-width manual-set" disabled={alreadyIn || currentSpecies.length >= state.environment.teamSize} onClick={() => onAdd({speciesId: species.id, itemId: null, abilityId: null, natureId: null, points: null, moves: [], level: 50, sourceKind: 'manual', sourceIds: []})}>自行填写配置</button>
    </div>}
  </aside>;
}
