import {useEffect, useMemo, useState} from 'react';
import {ArrowRight, Calculator, ChevronDown, Shield, Swords} from 'lucide-react';
import type {BattleField, DamageResult, PokemonSet} from '../../../../packages/core/types';
import {BattleConditions} from './BattleConditions';
import {ConditionTemplates} from './ConditionTemplates';
import {RiskPanel} from './RiskPanel';
import type {Workspace} from './useWorkspace';
import {Modal, PokemonIcon, SearchSelect, Spinner, useDex, OriginBadge} from './ui';

export function DamageDrawer({pair, workspace: w, onClose}: {pair: {attacker: PokemonSet; defender: PokemonSet; field?: BattleField} | null; workspace: Workspace; onClose: () => void}) {
  const dex = useDex(); const [attacker, setAttacker] = useState<PokemonSet | null>(null); const [defender, setDefender] = useState<PokemonSet | null>(null);
  const [riskOpen, setRiskOpen] = useState(false);
  const [field, setField] = useState<BattleField>({attackerMega: true, defenderMega: true}); const [results, setResults] = useState<DamageResult[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => {if (pair) {setAttacker(pair.attacker); setDefender(pair.defender); setField(pair.field || {attackerMega: true, defenderMega: true}); setResults([]); setError('');}}, [pair]);
  useEffect(() => {if (!pair || !attacker || !defender || !w.draft) return; let active = true; setBusy(true); setError(''); const timer = setTimeout(() => {void window.poke.call('damage', {attacker, defender, field, environmentId: w.draft!.environmentId}).then(data => {if (active) setResults(data);}).catch(err => {if (active) setError(err.message);}).finally(() => {if (active) setBusy(false);});}, 150); return () => {active = false; clearTimeout(timer);};}, [pair, attacker, defender, field, w.draft?.environmentId]);
  const candidates = w.state?.model.archetypes || [];
  const update = (patch: Partial<BattleField>) => setField(old => ({...old, ...patch}));
  return <Modal open={!!pair} onClose={onClose} title="伤害与生存阈值" description="计算真实配置的伤害区间，逐项切换实战条件。" drawer>{attacker && defender && <><div className="damage-matchup"><div><PokemonIcon id={attacker.speciesId} gender={attacker.gender} itemId={attacker.itemId} mega={field.attackerMega ?? true} size={85}/><strong>{dex.names('species', attacker.speciesId)}</strong><span>{dex.names('items', attacker.itemId)}</span></div><Swords size={24}/><div><PokemonIcon id={defender.speciesId} gender={defender.gender} itemId={defender.itemId} mega={field.defenderMega ?? true} size={85}/><strong>{dex.names('species', defender.speciesId)}</strong><span>{dex.names('items', defender.itemId)}</span></div></div><div className="damage-selectors"><SearchSelect label="我方成员" value={w.draft?.members.find(m => m.set.speciesId === attacker.speciesId)?.id || null} options={w.draft?.members.map(m => ({id: m.id, name: dex.speciesById.get(m.set.speciesId)?.name || m.set.speciesId, zh: dex.names('species', m.set.speciesId)})) || []} onChange={id => {const member = w.draft?.members.find(m => m.id === id); if (member) setAttacker(member.set);}}/><SearchSelect label="对手配置" value={candidates.find(a => JSON.stringify(a.representative) === JSON.stringify(defender))?.id || null} options={candidates.map(a => ({id: a.id, name: `${dex.speciesById.get(a.speciesId)?.name} ${a.label}`, zh: `${dex.names('species', a.speciesId)} · ${a.label}`}))} onChange={id => setDefender(candidates.find(a => a.id === id)!.representative)}/></div>
    <BattleConditions field={field} onChange={setField}/><details className="research-evidence"><summary>条件模板与范围检验</summary><ConditionTemplates w={w} attacker={attacker} defender={defender} field={field} onLoad={(a, d, f) => {setAttacker(a); setDefender(d); setField(f);}}/></details>
    <details className="research-evidence" onToggle={event => setRiskOpen(event.currentTarget.open)}><summary>命中风险与替代路线</summary>{riskOpen && <RiskPanel environmentId={w.draft!.environmentId} attacker={attacker} defender={defender} field={field}/>}</details>
    <p className="field-help">{[field.attackerTailwind && '我方顺风', field.defenderTailwind && '对手顺风', field.trickRoom && '戏法空间', field.attackerBoosts?.spe && `我方速度等级 ${field.attackerBoosts.spe}`, field.defenderBoosts?.spe && `对手速度等级 ${field.defenderBoosts.spe}`, field.attackerStatus && `我方状态 ${field.attackerStatus}`, field.defenderStatus && `对手状态 ${field.defenderStatus}`].filter(Boolean).join(' · ')}</p>{busy && <Spinner label="计算伤害区间"/>}{error && <div className="notice warning" role="alert">{error}</div>}<div className={`damage-results ${busy ? 'calculating' : ''}`}>{results.map(r => <article className="damage-card" key={r.moveId}><div className="damage-heading"><h3>{dex.names('moves', r.moveId)}</h3><span className={`ko-label ${r.ohko === 1 ? 'guaranteed' : ''}`}>{r.ohko === 1 ? '必定一击击杀' : r.ohko > 0 ? `${(r.ohko * 100).toFixed(1)}% 一击击杀` : '不能一击击杀'}</span></div><div className="damage-numbers"><strong>{r.minPercent.toFixed(1)}<span> — </span>{r.maxPercent.toFixed(1)}<small>%</small></strong><span>{r.min}–{r.max} / {r.defenderHP} HP</span></div><div className="damage-track"><span style={{width: `${Math.min(100, r.maxPercent)}%`}}/><i style={{width: `${Math.min(100, r.minPercent)}%`}}/></div><p>{r.condition}</p><p className="move-accuracy">{dex.moves.find(m => m.id === r.moveId)?.accuracy === true ? '该招式不进行基础命中率判定' : `基础命中率 ${dex.moves.find(m => m.id === r.moveId)?.accuracy}%`}；实际效果仍取决于特性、天气及其他招式条件。</p><details><summary>查看计算依据 <ChevronDown size={13}/></summary><p className="damage-description">{r.description}</p><small>可能伤害值：{r.rolls.join(' / ')}</small></details></article>)}</div><p className="analysis-note">“必定”要求满足全部伤害乱数，并考虑所选 HP 下的气腰与结实。这里的击杀概率以招式命中为条件，不包含命中率或要害。</p></>}</Modal>;
}
