import {useState} from 'react';
import {ArrowRight, ArrowUpRight, Check, CircleCheck, Database, Download, FileCode2, FolderOpen, Globe2, Plus, RefreshCw, ShieldCheck, Square, Trash2, X} from 'lucide-react';
import type {SourceTeam, TeamDraft, UpdateResult, ValidationIssue} from '../../../../packages/core/types';
import type {Workspace} from './useWorkspace';
import {RoleKnowledge} from './RoleKnowledge';
import {SourceRegistry} from './SourceRegistry';
import {StoragePanel} from './StoragePanel';
import {DocumentLibrary} from './DocumentLibrary';
import {ModelDiagnostics} from './ModelDiagnostics';
import {EnvironmentBenchmarks} from './EnvironmentBenchmarks';
import {IconButton, Modal, Spinner, useDex} from './ui';

export function Environment({workspace: w, onSource}: {workspace: Workspace; onSource: (source: SourceTeam) => void}) {
  const state = w.state!; const dex = useDex(); const active = state.environments.find(e => e.id === state.activeEnvironmentId)!;
  const [sources, setSources] = useState(state.corpus.reports.map(r => ({season: r.season, gid: r.gid})));
  const [checking, setChecking] = useState(false); const [check, setCheck] = useState<string | null>(null); const [localPath, setLocalPath] = useState(''); const [format, setFormat] = useState(active.formatId); const [advanced, setAdvanced] = useState(false);
  const [viewSeason, setViewSeason] = useState<string | null>(null); const [sourceQuery, setSourceQuery] = useState(''); const [sourceStatus, setSourceStatus] = useState('all'); const [page, setPage] = useState(0);
  const [migration, setMigration] = useState<{draft: TeamDraft; issues: ValidationIssue[]} | null>(null);
  const updateJob = w.jobs.find(j => j.kind === 'engine'); const syncJob = w.jobs.find(j => j.kind === 'sync');
  const update = updateJob?.result && 'environment' in updateJob.result ? updateJob.result as UpdateResult : null;
  const busy = updateJob?.status === 'running'; const syncing = syncJob?.status === 'running';
  const checkUpdate = async () => {setChecking(true); try {const result = await window.poke.call('checkUpdates', undefined); setCheck(result.available ? `发现上游更新 · ${result.revision.slice(0, 10)}` : '已是当前上游版本');} catch (err) {w.report(err);} finally {setChecking(false);}};
  const prepare = async (source: 'official' | 'local') => {try {await window.poke.call('prepareUpdate', {source, localPath: source === 'local' ? localPath : undefined, formatId: format});} catch (err) {w.report(err);}};
  const activate = async (id: string) => {try {await window.poke.call('activateEnvironment', {environmentId: id}); await w.refresh();} catch (err) {w.report(err);}};
  const migrate = async (environmentId: string) => {if (!w.draft) return; try {setMigration(await window.poke.call('migrateDraft', {draft: w.draft, environmentId}));} catch (err) {w.report(err);}};
  const sourceRows = state.corpus.teams.filter(t => t.season === viewSeason && `${t.description} ${t.author} ${t.id}`.toLowerCase().includes(sourceQuery.toLowerCase()) && (sourceStatus === 'all' || t.status === sourceStatus));
  return <main className="page environment-page"><div className="page-heading"><div><div className="eyebrow">ENVIRONMENT / {state.environment.season}</div><h1>读懂环境，找到突破口。</h1><p>查看真实配置的速度、输出和耐久，带着明确的对局目标调整队伍。</p></div><button className="button secondary" disabled={checking || busy} onClick={() => {document.querySelector<HTMLDetailsElement>('.environment-management')?.setAttribute('open', ''); void checkUpdate();}}>{checking ? <Spinner/> : <><RefreshCw size={16}/>检查上游更新</>}</button></div>
    <div className="environment-rule-strip"><span className="badge green"><CircleCheck size={12}/>{state.environment.season} · 当前队伍环境</span><span>{state.environment.teamSize} 只构筑 / 选出 {state.environment.pickedTeamSize} 只</span><span>{state.environment.points.total} 总点数 · 单项 {state.environment.points.perStat} 点</span><span>数据更新 {new Date(state.corpus.updatedAt).toLocaleDateString('zh-CN')}</span></div>
    <EnvironmentBenchmarks workspace={w} onSource={onSource}/>
    <details className="environment-management"><summary><span><Database size={18}/>规则与数据管理</span><small>更新规则、同步来源、查看环境快照</small></summary><div className="environment-management-content">
    <section className="environment-hero"><div className="environment-mark"><Globe2 size={36}/></div><div><span className="badge green"><CircleCheck size={12}/>当前启用</span><h2>Champions {active.season}</h2><p>{active.name}</p><div className="rule-chips"><span>{active.teamSize} 只构筑 · 选出 {active.pickedTeamSize} 只</span><span>{active.points.total} 总点数</span><span>单项 {active.points.perStat} 点</span><span>双打排位</span></div></div><div className="environment-version"><span>SHOWDOWN SNAPSHOT</span>{active.sourceRevision.startsWith('local:') ? <code>本地 {active.sourceRevision.slice(6, 18)}</code> : <button className="text-button" onClick={() => void window.poke.openExternal(`https://github.com/smogon/pokemon-showdown/commit/${active.sourceRevision}`)}>{active.sourceRevision.slice(0, 12)} <ArrowUpRight size={13}/></button>}<small>{new Date(active.generatedAt).toLocaleDateString('zh-CN')} 生成</small></div></section>
    <div className="environment-columns"><section className="surface"><div className="section-heading"><h2><RefreshCw size={17}/>规则更新</h2><span className="badge lavender">先验证，再切换</span></div><p className="muted">更新会重新解析规则、校验配置、重建模型，并保留旧快照。</p>{check && <div className="notice neutral">{check}</div>}<label className="form-field">目标对战格式<input aria-label="目标对战格式" value={format} onChange={e => setFormat(e.target.value)} spellCheck={false}/></label><button className="button primary full-width" disabled={busy} onClick={() => void prepare('official')}><Download size={16}/>从 Showdown 准备候选环境</button><button className="text-button advanced-toggle" onClick={() => setAdvanced(!advanced)}><FolderOpen size={14}/>使用本地 Showdown 文件</button>{advanced && <div className="local-source"><p>选择包含 sim、data 和 config 的检出目录。编译结果独立保存，复用当前伤害库，可离线迭代规则数据。</p><div className="button-row"><input aria-label="本地 Showdown 目录" value={localPath} onChange={e => setLocalPath(e.target.value)} placeholder="/path/to/pokemon-showdown"/><button className="button secondary" onClick={() => void window.poke.chooseDirectory().then(path => path && setLocalPath(path)).catch(w.report)}>选择目录</button></div><button className="button secondary full-width" disabled={!localPath || busy} onClick={() => void prepare('local')}>读取并验证本地规则</button></div>}{updateJob && <div className={`job-status ${updateJob.status}`}>{busy && <Spinner label="准备候选快照"/>}<p>{updateJob.message}</p>{updateJob.error && <p className="warning-text">{updateJob.error}</p>}{busy && <button className="text-button" onClick={() => void window.poke.call('cancelJob', {id: updateJob.id}).catch(w.report)}><Square size={12}/>取消更新</button>}</div>}{update && updateJob?.status === 'completed' && <div className="update-preview"><h3>候选环境差异</h3><div className="rule-chips"><span>新增 {update.addedSpecies.length}</span><span>移除 {update.removedSpecies.length}</span><span>宝可梦变化 {update.changedSpecies.length}</span><span>招式变化 {update.changedMoves.length}</span><span>道具变化 {update.changedItems.length}</span><span>特性变化 {update.changedAbilities.length}</span></div>{update.addedSpecies.length > 0 && <p>新增：{update.addedSpecies.map(s => dex.names('species', s)).join('、')}</p>}{update.removedSpecies.length > 0 && <p>移除：{update.removedSpecies.map(s => dex.names('species', s)).join('、')}</p>}{update.changedSpecies.length > 0 && <p>配置数据变化：{update.changedSpecies.map(s => dex.names('species', s)).join('、')}</p>}<ul>{update.tests.map(t => <li key={t}>{t}</li>)}</ul><button className="button primary full-width" disabled={update.environment.id === state.activeEnvironmentId} onClick={() => void activate(update.environment.id)}><Check size={15}/>{update.environment.id === state.activeEnvironmentId ? '已启用' : '启用这个环境'}</button></div>}</section>
    <section className="surface"><div className="section-heading"><h2><Database size={17}/>共享构筑来源</h2><span className="badge neutral">真实公开数据</span></div><p className="muted">当前赛季用于样本频率；历史配置通过本规则校验后，可提供配置参考与推断先验。</p>{state.environment.id !== state.activeEnvironmentId && <div className="notice neutral">当前队伍与下方来源仍关联 {state.environment.season} 的旧快照。新建或迁移队伍后，可为新环境同步对应分表。</div>}<div className="source-reports">{state.corpus.reports.map(r => <button className="source-report" key={`${r.documentId}:${r.gid}`} onClick={() => {setViewSeason(r.season); setPage(0); setSourceStatus('all');}}><span className={`season-chip ${r.season === state.environment.season ? 'current' : ''}`}>{r.season}</span><div><strong>{r.rows.toLocaleString()} 份来源</strong><p>{r.complete} 完整 · {r.partial} 缺字段 · {r.invalid} 待修正</p>{!!r.missingColumns?.length && <p className="warning-text">缺少元数据列：{r.missingColumns.join('、')}，相关字段按未知保留</p>}</div><span className={r.failed ? 'warning-text' : 'success-text'}>{r.failed ? `${r.failed} 读取失败` : <ShieldCheck size={17}/>}</span><ArrowUpRight size={14}/></button>)}</div><SourceRegistry workspace={w}/><p className="field-help">数据时间：{new Date(state.corpus.updatedAt).toLocaleString('zh-CN')}。转贴保留来源，统计按完整配置归组。</p></section></div>
    <section className="surface saved-environments"><div className="section-heading"><h2>保存的环境快照</h2><span className="muted">已有队伍继续关联原环境</span></div>{state.environments.map(env => <div className="environment-row" key={env.id}><FileCode2 size={20}/><div><strong>{env.name}</strong><span>{env.sourceRevision.slice(0, 12)} · calc {env.calcRevision.slice(0, 12)} · {new Date(env.generatedAt).toLocaleDateString('zh-CN')}</span></div>{env.id === state.activeEnvironmentId ? <span className="badge green">当前启用</span> : <button className="button small secondary" onClick={() => void activate(env.id)}>启用</button>}{w.draft?.environmentId !== env.id && <button className="text-button" onClick={() => void migrate(env.id)}>迁移当前队伍 <ArrowRight size={13}/></button>}</div>)}<p className="field-help">本地数据保存在 {state.dataDirectory}</p></section><StoragePanel/></div></details>
    <RoleKnowledge workspace={w}/><ModelDiagnostics model={state.model}/><DocumentLibrary workspace={w}/>
    <Modal open={!!viewSeason} onClose={() => setViewSeason(null)} title={`${viewSeason} 来源记录`} description="缺失字段与规则冲突单独保留，不会被自动补成零或混入精算。" wide><div className="source-browser-tools"><input aria-label="筛选构筑来源" value={sourceQuery} onChange={e => {setSourceQuery(e.target.value); setPage(0);}} placeholder="搜索作者、说明或队伍编号"/><select aria-label="筛选来源状态" value={sourceStatus} onChange={e => {setSourceStatus(e.target.value); setPage(0);}}><option value="all">全部状态</option><option value="valid">完整合法</option><option value="partial">缺失字段</option><option value="invalid">规则冲突</option><option value="fetch-error">读取失败</option></select></div><div className="source-browser-list">{sourceRows.slice(page * 20, (page + 1) * 20).map(t => <button key={t.id} onClick={() => onSource(t)}><span className="source-row-id">{t.id.split(':')[1]}</span><div><strong>{t.description}</strong><small>{t.author} · {t.date}</small></div><span className={`source-status ${t.status}`}>{({valid: '完整', partial: '缺字段', invalid: '待修正', 'fetch-error': '失败'})[t.status]}</span><ArrowUpRight size={14}/></button>)}</div><div className="pagination"><span>{sourceRows.length} 份来源 · 第 {page + 1} 页</span><button className="button small secondary" disabled={!page} onClick={() => setPage(page - 1)}>上一页</button><button className="button small secondary" disabled={(page + 1) * 20 >= sourceRows.length} onClick={() => setPage(page + 1)}>下一页</button></div></Modal>
    <Modal open={!!migration} onClose={() => setMigration(null)} title="迁移预览" description="迁移会创建一份新队伍，原队伍与其环境记录保留。">{migration && <><h3>{migration.draft.name}</h3>{migration.issues.length ? <div className="notice warning">{migration.issues.map((v, i) => <p key={i}>{v.message}</p>)}</div> : <div className="notice success">现有配置在目标环境中合法。</div>}<p className="muted">能力点、招式和初始特性原样保留。规则冲突会在新草稿中显示，等待你调整。</p><div className="dialog-footer"><button className="button primary" onClick={() => void w.selectDraft(migration.draft).then(() => setMigration(null)).catch(w.report)}>创建迁移后的队伍</button></div></>}</Modal>
  </main>;
}
