import {useState} from 'react';
import {ArrowRight, Copy, History, Plus, Trash2, LockKeyhole, Check} from 'lucide-react';
import type {TeamDraft} from '../../../../packages/core/types';
import type {Workspace} from './useWorkspace';
import {IconButton, Modal, PokemonIcon, useDex} from './ui';

export function MyTeams({workspace: w, onOpen}: {workspace: Workspace; onOpen: () => void}) {
  const [deleting, setDeleting] = useState<TeamDraft | null>(null); const [versions, setVersions] = useState<TeamDraft[] | null>(null); const [historyTeam, setHistoryTeam] = useState<TeamDraft | null>(null); const [selected, setSelected] = useState<TeamDraft | null>(null); const dex = useDex();
  const history = async (draft: TeamDraft) => {try {await w.flush(); setVersions(await window.poke.call('history', {id: draft.id})); setHistoryTeam(draft); setSelected(null);} catch (err) {w.report(err);}};
  const restore = async () => {if (!selected || !historyTeam) return; try {await w.selectDraft(w.state!.drafts.find(d => d.id === historyTeam.id)!); w.edit(d => ({...selected, revision: d.revision})); setVersions(null); onOpen();} catch (err) {w.report(err);}};
  return <main className="page teams-page"><div className="page-heading"><div><div className="eyebrow">YOUR COLLECTION</div><h1>每一个构筑思路，都留在这里<span>。</span></h1><p>本地自动保存。队伍的每次修改都可以回看与恢复。</p></div><button className="button primary" onClick={() => void w.create().then(onOpen).catch(w.report)}><Plus size={17}/>新建队伍</button></div><div className="saved-teams-grid">{w.state!.drafts.map(d => <article className="saved-team" key={d.id}><div className="saved-team-heading"><span className="badge neutral">{w.state!.environments.find(e => e.id === d.environmentId)?.season || '旧环境'}</span><span className={d.members.length === 6 ? 'success-text' : 'muted'}>{d.members.length === 6 ? '六人队伍' : `${d.members.length} / 6 · 构筑中`}</span></div><button className="saved-team-open" onClick={() => void w.selectDraft(d).then(onOpen).catch(w.report)}><h2>{d.name || '未命名队伍'}</h2><div className="saved-team-lineup">{Array.from({length: 6}, (_, i) => d.members[i] ? <span key={i}><PokemonIcon id={d.members[i].set.speciesId} size={48}/>{d.members[i].lock.species && <LockKeyhole size={10}/>}</span> : <span className="empty" key={i}><Plus size={15}/></span>)}</div><p>{d.notes || '为这支队伍寻找下一种可能。'}</p></button><div className="saved-team-footer"><small>{new Date(d.updatedAt).toLocaleString('zh-CN', {month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'})}</small><div><IconButton label={`查看${d.name}的历史`} onClick={() => void history(d)}><History size={16}/></IconButton><IconButton label={`复制${d.name}`} onClick={() => void w.selectDraft({...structuredClone(d), id: crypto.randomUUID(), revision: 0, name: `${d.name} · 副本`, updatedAt: new Date().toISOString()}).then(onOpen).catch(w.report)}><Copy size={15}/></IconButton><IconButton label={`删除${d.name}`} onClick={() => setDeleting(d)}><Trash2 size={15}/></IconButton></div></div></article>)}</div>
    <Modal open={!!deleting} onClose={() => setDeleting(null)} title="删除本地队伍" description="删除后该队伍及其版本历史会从本地移除。">{deleting && <><p>删除「{deleting.name}」？</p><div className="dialog-footer"><button className="button secondary" onClick={() => setDeleting(null)}>保留队伍</button><button className="button danger-solid" onClick={() => {void (async () => {await w.flush(); const id = deleting.id; if (id === w.draft?.id) await w.create(); await window.poke.call('deleteDraft', {id}); await w.refresh(); setDeleting(null);})().catch(w.report);}}>删除队伍</button></div></>}</Modal>
    <Modal open={!!versions} onClose={() => setVersions(null)} title={`${historyTeam?.name || ''} · 版本历史`} description="恢复历史会生成一个新修订，不会覆盖原记录。" wide><div className="history-layout"><div className="history-list">{versions?.map(v => <button className={selected?.revision === v.revision ? 'selected' : ''} key={v.revision} onClick={() => setSelected(v)}><strong>修订 {v.revision}</strong><span>{new Date(v.updatedAt).toLocaleString('zh-CN')}</span><small>{v.members.length} 位成员</small></button>)}</div><div className="history-preview">{selected ? <><h3>{selected.name}</h3>{selected.members.map(m => <div className="comparison-member" key={m.id}><PokemonIcon id={m.set.speciesId} size={44}/><div><strong>{dex.names('species', m.set.speciesId)}</strong><span>{dex.names('items', m.set.itemId)} · {dex.names('natures', m.set.natureId)}</span><small>{m.set.moves.map(id => dex.names('moves', id)).join(' / ')}</small><small>{m.set.points && Object.values(m.set.points).join(' / ')}</small></div></div>)}<button className="button primary" onClick={() => void restore()}><Check size={15}/>恢复这个版本</button></> : <p className="muted">选择一个历史版本查看配置。</p>}</div></div></Modal>
  </main>;
}
