import {useState} from 'react';
import type {MaintenanceReport} from '../../../../packages/core/maintenance';
import {Modal, Spinner} from './ui';

const bytes = (value: number) => value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(2)} GB` : `${(value / 1024 ** 2).toFixed(2)} MB`;
const labels: Record<string, string> = {drafts: '队伍', history: '队伍历史', research_entries: '研究与实战记录', jobs: '分析任务与完整回放', environments: '规则快照', corpora: '构筑原文及观察', models: '配置模型', analysis_cache: '可重算的分析缓存', source_registry: '来源注册表'};
export function StoragePanel() {
  const [report, setReport] = useState<MaintenanceReport | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [preview, setPreview] = useState(false);
  const [choices, setChoices] = useState({analysisCache: false, unusedVersions: false, compact: false, memoryCache: false});
  const refresh = async () => {setBusy(true); setError(''); try {setReport(await window.poke.call('maintenance', undefined));} catch (e) {setError((e as Error).message);} finally {setBusy(false);}};
  const clean = async () => {setBusy(true); setError(''); try {await window.poke.call('cleanStorage', {...choices, planHash: report!.storage.plan.hash}); setPreview(false); await refresh();} catch (e) {setError((e as Error).message);} finally {setBusy(false);}};
  return <details className="surface knowledge-panel"><summary>本地存储与运行占用</summary><p className="muted">查看各数据版本和计算上下文的占用。清理由你选择，队伍、研究记录和回放所需版本始终保留。</p><button className="button secondary" disabled={busy} onClick={() => void refresh()}>{busy ? <Spinner/> : '读取当前占用'}</button><p className="field-help">线程统计在该线程当前计算完成后返回。内存释放由运行时回收，清空缓存不保证进程占用立即下降。</p>{error && <p className="notice warning" role="alert">{error}</p>}{report && <>
    <div className="table-scroll"><table><caption>数据库中的内容大小（文件大小另列）</caption><thead><tr><th>内容</th><th>条数</th><th>大小</th></tr></thead><tbody>{report.storage.tables.map(row => <tr key={row.table}><th scope="row">{labels[row.table]}</th><td>{row.rows.toLocaleString()}</td><td>{bytes(row.bytes)}</td></tr>)}</tbody></table></div>
    <p>{report.storage.disk.map(row => `${row.name}：${bytes(row.bytes)}`).join(' · ')}</p>
    <div className="table-scroll"><table><caption>计算上下文；进程实际内存 {bytes(report.runtime[0].rss)}（共享值，不逐行累加）</caption><thead><tr><th>进程／线程</th><th>已用堆</th><th>模型上下文</th><th>伤害缓存条数</th></tr></thead><tbody>{report.runtime.map(row => <tr key={row.process}><th>{({service: '本地服务', fast: '快速分析', deep: '深入计算', maintenance: '数据更新'})[row.process]}</th><td>{bytes(row.heapUsed)}</td><td>{row.contexts.length}</td><td>{row.contexts.reduce((sum, c) => sum + c.damageEntries, 0).toLocaleString()}</td></tr>)}</tbody></table></div>
    <fieldset className="cleanup-options"><legend>选择维护内容</legend>{([['analysisCache', '删除可重算的分析缓存'], ['memoryCache', '释放模型上下文与内存缓存'], ['unusedVersions', `删除没有记录引用的旧语料／模型（${report.storage.plan.corpora.length + report.storage.plan.models.length} 个，${bytes(report.storage.plan.removableBytes)}）`], ['compact', '压缩数据库空闲页']] as const).map(([id, label]) => <label className="checkbox-label" key={id}><input type="checkbox" checked={choices[id]} onChange={e => setChoices({...choices, [id]: e.target.checked})}/>{label}</label>)}</fieldset>
    <button className="button secondary" disabled={busy || !Object.values(choices).some(Boolean)} onClick={() => setPreview(true)}>预览所选清理</button>
  </>}<Modal open={preview} onClose={() => setPreview(false)} title="确认清理预览" description="只清理你选中的缓存与无引用版本。队伍历史、来源原文、实战和回放记录保留。"><p>{choices.analysisCache && `删除 ${report?.storage.plan.cacheRows} 条分析缓存。`}{choices.memoryCache && '计算线程完成当前任务后释放上下文。'}{choices.compact && '重写数据库以回收空闲页。'}</p>{choices.unusedVersions && <details open><summary>不再被任何记录引用的版本</summary><pre className="paste-text">{[...(report?.storage.plan.models ?? []), ...(report?.storage.plan.corpora ?? [])].join('\n') || '没有符合条件的版本'}</pre></details>}<button className="button primary" disabled={busy} onClick={() => void clean()}>{busy ? <Spinner/> : '执行所选清理'}</button></Modal></details>;
}
